# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.1"
manifest_format = "2.0"
project_hash = "db70adac55adf6c26e9c4c354c423b0adb0de6be"

[[deps.AdventOfCode]]
git-tree-sha1 = "347f5c4af3a88172c07f1bd2aad3a85ba03385c7"
repo-rev = "v0.6.0"
repo-url = "https://github.com/jakewilliami/AdventOfCode.jl"
uuid = "12c762d1-ec83-4627-b0f9-c32bfcd79ad0"
version = "0.6.0"

[[deps.Combinatorics]]
git-tree-sha1 = "08c8b6831dc00bfea825826be0bc8336fc369860"
uuid = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
version = "1.0.2"
