# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.1"
manifest_format = "2.0"
project_hash = "079c1aad4f4aa1198bbaafc3a245848f03d15774"

[[deps.AdventOfCode]]
git-tree-sha1 = "4d4454a5f5beac864a484fec07d0fe59736323ab"
repo-rev = "v0.2.2"
repo-url = "https://github.com/jakewilliami/AdventOfCode.jl"
uuid = "12c762d1-ec83-4627-b0f9-c32bfcd79ad0"
version = "0.2.2"
